[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = espidf
monitor_speed = 115200
board_build.embed_txtfiles = src/web/index.html
board_build.partitions = partitions.csv