[wokwi]
version = 1
firmware = ".pio/build/heltec_wifi_lora_32_V3/firmware.bin"
elf = ".pio/build/heltec_wifi_lora_32_V3/firmware.elf"

# Пробрасываем 80 порт ESP32 (веб-сервер) на 8180 порт локального компьютера
[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = 'bmp280'
# Скомпилировано из bmp280.chip.c командой:
#   wokwi-cli chip compile bmp280.chip.c -o bmp280.chip.wasm
# В diagram.json чип используется как "type": "chip-bmp280"
binary = 'bmp280.chip.wasm'

[[chip]]
name = 'motor610'
# Скомпилировано из motor610.chip.c командой:
#   wokwi-cli chip compile motor610.chip.c -o motor610.chip.wasm
# В diagram.json чип используется как "type": "chip-motor610"
binary = 'motor610.chip.wasm'